version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - mylocal
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres


  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - mylocal
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
networks:
  mylocal:
    driver: bridge