basePath: /api
definitions:
  models.AddressGeo:
    description: AddressGeo represents the geocode result for an address.
    properties:
      suggestions:
        items:
          properties:
            data:
              properties:
                country:
                  type: string
                postal_code:
                  type: string
              type: object
            unrestricted_value:
              type: string
            value:
              type: string
          type: object
        type: array
    type: object
  models.AddressSearch:
    description: AddressSearch represents the search result for an address.
    properties:
      metro:
        items:
          properties:
            distance:
              type: number
            line:
              type: string
            name:
              type: string
          type: object
        type: array
      result:
        type: string
      source:
        type: string
    type: object
  models.GeocodeRequest:
    description: GeocodeRequest represents the request body for address geocoding.
    properties:
      lat:
        type: string
      lon:
        type: string
    type: object
  models.SearchRequest:
    description: SearchRequest represents the request body for address search
    properties:
      query:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample API for address searching and geocoding using Dadata
    API.
  termsOfService: http://localhost:8080/swagger/index.html
  title: My API
  version: "1.1"
paths:
  /address/geocode:
    post:
      consumes:
      - application/json
      operationId: geocodeAddress
      parameters:
      - description: Geocode request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.GeocodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AddressGeo'
        "500":
          description: Internal Server Error
      summary: Geocode an address
      tags:
      - geocode
  /address/search:
    post:
      consumes:
      - application/json
      operationId: searchAddress
      parameters:
      - description: Search request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SearchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AddressSearch'
        "500":
          description: Internal Server Error
      summary: Search for an address
      tags:
      - search
swagger: "2.0"
